### ISSUE TITLE
Unable to find pyVolLib

### ISSUE THREAD

**Issue by tzw5099** [jensolson/SPX-Gamma-Exposure#1]
Hi there,

I'm unable to pip install pyVolLib and have been unable to find the package from Google searches.

Are you using py_vollib? http://vollib.org/documentation/python/1.0.2/
Simply replacing "pyVolLib" with "py_vollib" doesn't work though. The modules you reference aren't in py_vollib.

If you're using a custom package or one you wrote yourself, would love if you can share.

Sincerely,

Tom

**Comment by jensolson** [comment]
Hi Tom, apologies for the delay. "pyVolLib" is a helper script that I created to work with the py_vollib module. I've uploaded the helper to my repository.
